# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-02 05:24
from __future__ import unicode_literals

import catalogue.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlayer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Application'),
        ),
        migrations.AlterField(
            model_name='applicationlayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Record'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborators', to='catalogue.Organization'),
        ),
        migrations.AlterField(
            model_name='pycswconfig',
            name='point_of_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Collaborator'),
        ),
        migrations.AlterField(
            model_name='record',
            name='legend',
            field=models.FileField(blank=True, null=True, storage=catalogue.models.OverwriteStorage(), upload_to=catalogue.models.legendFilePath),
        ),
        migrations.AlterField(
            model_name='record',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Maps to pycsw:Modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='source_legend',
            field=models.FileField(blank=True, editable=False, null=True, storage=catalogue.models.OverwriteStorage(), upload_to=catalogue.models.sourceLegendFilePath),
        ),
        migrations.AlterField(
            model_name='style',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='catalogue.Record'),
        ),
    ]
